version: '3.5'

services:
  node:
    build:
      context: .docker/node
      dockerfile: Dockerfile
    working_dir: /app
    user: "node:node"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8004:4000"
    command: ["npm", "run", "watch"]

  nginx:
    build:
      dockerfile: Dockerfile
      context: .docker/nginx
      args:
        TZ: "Asia/Shanghai"
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/conf/app.conf.template:/etc/nginx/conf.d/app.conf.template
      - .docker/nginx/letsencrypt:/etc/letsencrypt
      - ./public:/data/sites/blog
