FROM node-base AS node-build
WORKDIR /app
COPY . /app
RUN npm install
# Build static pages
RUN npm run clean && npm run build


FROM nginx-base
# Copy statics into webservice
COPY --from=node-build /app/public /data/sites/blog
COPY .docker/nginx/conf/nginx.conf /etc/nginx/nginx.conf
COPY .docker/nginx/letsencrypt /etc/letsencrypt
COPY .docker/nginx/conf/app.conf.template /etc/nginx/conf.d/app.conf.template
