name: "Deploy"

on:
  push:
    branches:
      - master
      - Setup_deploy_action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Install Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: "Install npm dependencies"
        run: npm install
      - name: "Run build pages"
        run: npm run clean && npm run build
      - name: "Deploy to Server"
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
